version: '3.8'

services:
  monitor:
    image: python:3.11-slim
    container_name: system-monitor
    volumes:
      - ./monitor.py:/monitor.py:ro
      - ./output:/output
    command: sh -c "pip install psutil speedtest-cli && python /monitor.py"

  nginx:
    image: nginx:alpine
    container_name: system-nginx
    volumes:
      - ./output:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
